addSbtPlugin("com.eed3si9n"       % "sbt-assembly"    % "0.12.0")
addSbtPlugin("com.typesafe.sbt"   % "sbt-pgp"         % "0.8.3")
addSbtPlugin("com.github.gseitz"  % "sbt-release"     % "0.8.5")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"    % "0.2.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.1.10")
addSbtPlugin("com.typesafe.sbt"   % "sbt-scalariform" % "1.3.0")
