addSbtPlugin("com.eed3si9n"       % "sbt-assembly"    % "0.12.0")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"   % "0.3.2")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"      % "1.1.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.1.11")
addSbtPlugin("com.typesafe.sbt"   % "sbt-pgp"         % "0.8.3")
addSbtPlugin("com.github.gseitz"  % "sbt-release"     % "0.8.5")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"   % "1.0.4")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"    % "0.2.1")
